### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by NoellyB76** [tolyo/ionic-brunch-es6-seed#1]
Hello,

I followed the directions as found on npmjs.org, and then decided to open an issue over here (as it seemed more appropriate to do so).

So, after trying:

npm start mobile

OR

npm start desktop

I get an error about npm start being undefined.

So I tried just running:

node app.js, also to no avail.

Here's my complete terminal input/output:

noel@nbdev:~/DEV/ionic-brunch/ionic-brunch-es6-seed$ npm start mobile
npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "mobile"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/noel/DEV/ionic-brunch/ionic-brunch-es6-seed/npm-debug.log
noel@nbdev:~/DEV/ionic-brunch/ionic-brunch-es6-seed$ npm start desktop
npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "desktop"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/noel/DEV/ionic-brunch/ionic-brunch-es6-seed/npm-debug.log
noel@nbdev:~/DEV/ionic-brunch/ionic-brunch-es6-seed$ ls
app         hooks          karma.conf.js  npm-debug.log
config.js   ionic.project  LICENSE        package.json
config.xml  karmaboot.js   node_modules   README.md
noel@nbdev:~/DEV/ionic-brunch/ionic-brunch-es6-seed$ cd app
noel@nbdev:~/DEV/ionic-brunch/ionic-brunch-es6-seed/app$ ls
AppConfig.js  app.js     app.scss  desktop.html  ionic-angular.js  modules
AppCtrl.js    AppRun.js  assets    index.html    ionic.js          styles
noel@nbdev:~/DEV/ionic-brunch/ionic-brunch-es6-seed/app$ node app.js
/home/noel/DEV/ionic-brunch/ionic-brunch-es6-seed/app/app.js:1
(function (exports, require, module, __filename, __dirname) { import angular from 'angular';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

I'm hoping this is just me being a complete noob or something, and that I'M the problem  :)

thanks in advance :)

**Comment by tolyo** [comment]
I apologize for not updating readme. Please try `npm run mobile`

**Comment by NoellyB76** [comment]
Oh my goodness... I didn't even think to check to look... I just assumed you hadn't defined anything at all.

Thanks! :)

**Comment by tolyo** [comment]
It was my fail.

**Comment by NoellyB76** [comment]
Noticed that you have an ionic version 2 Brunch ES6 seed in the works.

What's the status of that? How much longer will it take for you to have
that pumped out?

If you need some help with it, I'm interested.

Thanks,
Noel

**Comment by tolyo** [comment]
Its done but there is an ionicons import issue I am not able to resolve. Give it a try please.
